# Generated by Django 4.1.1 on 2022-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AISite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_no",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
