# Generated by Django 4.1.1 on 2022-09-25 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AISite", "0003_user_dob_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(verbose_name=datetime.timezone),
        ),
    ]
