# Generated by Django 4.1.1 on 2022-09-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AISite", "0009_remove_user_phone_no_remove_user_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
